name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@ef9c2745dbfb629d38ebfafa3347a81ab2d51409 # v4.4.1
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
